// Code generated by internal/tools/facadegen; DO NOT EDIT.
// Regenerate with: go generate ./...
//
// This is the public API of github.com/rhaqim/loom. Every declaration is a
// re-export of internal/engine: types are aliases (identical types across the
// boundary), and consts/vars/funcs are value re-exports. Docs are copied from
// the source declarations in internal/engine, which remain the single source of
// truth. Sections group the surface by domain.

package loom

import engine "github.com/rhaqim/loom/internal/engine"

// Engine, configuration & core types
// ----------------------------------

// Dialect identifies the database flavour for the schema loader.
type Dialect = engine.Dialect

const DialectPostgres = engine.DialectPostgres

const DialectSQLite = engine.DialectSQLite

// Config is the top-level engine configuration.
type Config = engine.Config

// Logger is the minimal logging interface the engine uses.
type Logger = engine.Logger

// Engine is the central object applications interact with.
type Engine = engine.Engine

// New creates and initialises a Loom engine from the given Config.
// It does NOT run schema migrations — call NewSchemaLoader(dialect).Apply(ctx, db) first.
var New = engine.New

// TaskResolution describes the terminal outcome of an async provider job,
// delivered to the callback registered with OnTaskResolved.
type TaskResolution = engine.TaskResolution

type JudgeRegistry = engine.JudgeRegistry

// GCService is the public interface returned by Engine.GC().
type GCService = engine.GCService

// MarshalResult serialises a Result to JSON for storage.
var MarshalResult = engine.MarshalResult

// Sessions & state
// ----------------

// Session is a running conversation. It holds state, action log, result history,
// and any custom data the platform attaches.
type Session = engine.Session

// State is the live state of a session between steps.
type State = engine.State

// BranchNode represents a node in the session branch tree.
type BranchNode = engine.BranchNode

// SessionRegistry manages session persistence and branching.
type SessionRegistry = engine.SessionRegistry

// Agents
// ------

// Agent is a configuration bundling a Generator, system prompt, user template,
// response format, and generation params. It is the unit the platform spawns.
type Agent = engine.Agent

// AgentRegistry resolves and manages agents.
type AgentRegistry = engine.AgentRegistry

// Prompts
// -------

// Prompt is a versioned, categorized text template stored in the database.
type Prompt = engine.Prompt

// ResponseFormatJSON builds a ResponseFormat from a raw JSON Schema string — the
// easy path for attaching an output schema to an agent (paste a client-authored
// schema straight in). An empty/blank raw yields a non-nil ResponseFormat with no
// schema, which generators treat as portable JSON mode. Response formats are
// independent of prompts: the same one can be reused across many agents, and an
// agent's system prompt, user template, and response format are each versioned
// and referenced independently.
var ResponseFormatJSON = engine.ResponseFormatJSON

// MustResponseFormatJSON is ResponseFormatJSON that panics on invalid JSON —
// convenient for static schemas defined in code.
var MustResponseFormatJSON = engine.MustResponseFormatJSON

// PromptKind discriminates between system and user template prompts.
type PromptKind = engine.PromptKind

const PromptKindSystem = engine.PromptKindSystem

const PromptKindUserTemplate = engine.PromptKindUserTemplate

// PromptRef is a lightweight pointer to a specific prompt version.
type PromptRef = engine.PromptRef

// PromptByName constructs a PromptRef for a specific slug+version.
var PromptByName = engine.PromptByName

// PromptFromFile constructs a PromptRef loaded from a file path.
var PromptFromFile = engine.PromptFromFile

// PromptRegistry resolves and manages prompts.
type PromptRegistry = engine.PromptRegistry

// Response formats
// ----------------

// ResponseFormatRecord is a stored, versioned response format.
type ResponseFormatRecord = engine.ResponseFormatRecord

// ResponseFormatRegistry resolves and manages reusable response formats.
type ResponseFormatRegistry = engine.ResponseFormatRegistry

// Actions
// -------

// ActionKind discriminates the shape of an Action's payload.
type ActionKind = engine.ActionKind

const ActionSelect = engine.ActionSelect

const ActionFreeText = engine.ActionFreeText

const ActionSpatial = engine.ActionSpatial

const ActionInventory = engine.ActionInventory

const ActionGesture = engine.ActionGesture

const ActionCustom = engine.ActionCustom

// Action is the discriminator's structured human-guidance input for a step.
type Action = engine.Action

// Selection is the payload for ActionSelect — choosing one of N presented options.
type Selection = engine.Selection

// FreeText is the payload for ActionFreeText — a user-typed string.
type FreeText = engine.FreeText

// Spatial is the payload for ActionSpatial — a direction or coordinate input.
type Spatial = engine.Spatial

// InventoryChoice is the payload for ActionInventory — selecting an item.
type InventoryChoice = engine.InventoryChoice

// Gesture is the payload for ActionGesture — pointer or touch input.
type Gesture = engine.Gesture

// ActionTemplate describes an action the engine offers back to the platform.
type ActionTemplate = engine.ActionTemplate

// RawInput is opaque user input the platform passes to an ActionInterpreter.
type RawInput = engine.RawInput

// ActionInterpreter converts raw platform input to a structured Action.
// The platform supplies this; the engine uses it internally during RunStep.
type ActionInterpreter = engine.ActionInterpreter

// Steps
// -----

// StoredRequest is a serialized GenerateRequest persisted alongside the step.
type StoredRequest = engine.StoredRequest

// StoredResult is a modality-typed result payload persisted in loom_results.
type StoredResult = engine.StoredResult

// Step is one iteration of the engine loop: build request → call agent → result → actions.
// Steps are append-only; they form the complete timeline of a session.
type Step = engine.Step

// RetryMode selects how the engine treats post-hook retries.
type RetryMode = engine.RetryMode

// RetryDiscard re-runs on a post-hook retry and discards the rejected
// attempt; exhausting the retry budget fails the step. This is the default.
const RetryDiscard = engine.RetryDiscard

// RetryKeepBest scores every attempt (post-hooks return ErrRetryScored) and
// persists the lowest-scoring draft. Exhausting the budget keeps the best
// draft instead of failing, a generator failure after attempt 0 keeps the
// best draft so far, and only attempt 0 streams (retries run silently).
const RetryKeepBest = engine.RetryKeepBest

// StepRequest is the input to RunStep.
type StepRequest = engine.StepRequest

// StepRunner executes a step request against a session.
type StepRunner = engine.StepRunner

// CostRecord is a lightweight view of a cost entry used in callbacks.
// The full type lives in the cost sub-package; this alias avoids an import cycle.
type CostRecord = engine.CostRecord

// Results
// -------

// ResultStatus indicates whether a Result is ready, pending, or failed.
type ResultStatus = engine.ResultStatus

const ResultStatusReady = engine.ResultStatusReady

const ResultStatusPending = engine.ResultStatusPending

const ResultStatusFailed = engine.ResultStatusFailed

// Result is the typed output produced by a Generator.
type Result = engine.Result

// TextResult is the output from a text-modality generator.
type TextResult = engine.TextResult

// ImageResult is the output from an image-modality generator.
type ImageResult = engine.ImageResult

// VideoResult is the output from a video-modality generator.
type VideoResult = engine.VideoResult

// AudioResult is the output from an audio-modality generator.
type AudioResult = engine.AudioResult

// WorldDelta is a single structured operation applied to a procedural world.
type WorldDelta = engine.WorldDelta

// WorldResult is the output from a world-modality generator.
type WorldResult = engine.WorldResult

// StructuredResult carries arbitrary typed JSON output.
type StructuredResult = engine.StructuredResult

// NewTextResult creates a ready TextResult.
var NewTextResult = engine.NewTextResult

// NewImageResult creates a ready ImageResult.
var NewImageResult = engine.NewImageResult

// NewVideoResult creates a ready VideoResult.
var NewVideoResult = engine.NewVideoResult

// NewAudioResult creates a ready AudioResult.
// url is the remote URL or data URI of the audio file.
// format is the MIME type or extension (e.g. "audio/mpeg", "mp3").
// durationSec is the audio length in seconds.
var NewAudioResult = engine.NewAudioResult

// NewPendingResult creates a pending Result for async generators.
var NewPendingResult = engine.NewPendingResult

// NewFailedResult creates a failed Result carrying the error message in metadata
// under "error". Streaming generators send this on the result channel to signal a
// provider failure so the engine surfaces it instead of persisting an empty
// successful turn.
var NewFailedResult = engine.NewFailedResult

// NewWorldResult creates a ready WorldResult.
var NewWorldResult = engine.NewWorldResult

// NewStructuredResult creates a ready StructuredResult.
var NewStructuredResult = engine.NewStructuredResult

// Generators
// ----------

// TaskHandle references an in-flight async provider job.
type TaskHandle = engine.TaskHandle

// GenerateParams holds per-call tuning knobs for the generator.
type GenerateParams = engine.GenerateParams

// ResponseFormat describes the expected JSON schema for structured output.
type ResponseFormat = engine.ResponseFormat

// GenerateRequest is the input to a Generator.
type GenerateRequest = engine.GenerateRequest

// Generator produces a Result from a GenerateRequest. One per modality+provider.
type Generator = engine.Generator

// Chunk carries a partial text fragment from a streaming generator.
type Chunk = engine.Chunk

// StreamingGenerator extends Generator with incremental chunk delivery.
// Only text-modality generators need to implement this interface.
type StreamingGenerator = engine.StreamingGenerator

// PollerConfig configures the background async result poller.
type PollerConfig = engine.PollerConfig

// Modality
// --------

// Modality is the output kind a generator produces.
type Modality = engine.Modality

const ModalityText = engine.ModalityText

const ModalityImage = engine.ModalityImage

const ModalityVideo = engine.ModalityVideo

const ModalityAudio = engine.ModalityAudio

const ModalityWorld = engine.ModalityWorld

const ModalityStructured = engine.ModalityStructured

// Flows & turns
// -------------

// FlowAgent is one agent participating in a turn.
type FlowAgent = engine.FlowAgent

// Flow declares a turn as a lead agent plus parallel followers.
type Flow = engine.Flow

// TurnRequest is the input to RunTurn.
type TurnRequest = engine.TurnRequest

// Turn is the result of RunTurn: the lead step plus follower steps, all sharing
// a single turn ID (recorded on each Step's Diagnostics as "turn_id").
type Turn = engine.Turn

// ResultText extracts the primary text payload from a Result for prompt
// injection, returning "" for modalities without a natural text form.
var ResultText = engine.ResultText

// Flow persistence
// ----------------

// FlowRecord is a persisted, versioned agent map.
type FlowRecord = engine.FlowRecord

// FlowAgentEntry is one agent's slot in a persisted flow.
type FlowAgentEntry = engine.FlowAgentEntry

// FlowRegistry resolves and manages persisted flows (agent maps). owner is an
// opaque scope ("" = global). On Get/Latest, version 0 resolves to the latest
// version; Create and Delete require an explicit version >= 1. Edits create a
// new version (like agents/prompts); Delete removes a specific version.
type FlowRegistry = engine.FlowRegistry

// Hooks
// -----

// PreHook runs before the agent. It may modify the request, cancel the step
// (return ErrSkip), or annotate the state. Hooks run in registration order.
type PreHook = engine.PreHook

// PostHook runs after the agent, before the result is persisted. It may
// validate, annotate, transform, or request a retry (return ErrRetryWith(...)).
type PostHook = engine.PostHook

// HookBus manages pre- and post-hook registration.
type HookBus = engine.HookBus

// Schema validation
// -----------------

// SchemaValidationPostHook returns a PostHook that validates a structured/text
// result against the resolved ResponseFormat schema. On any violation it returns
// ErrRetryWith so the engine re-runs the agent with the violations as the reason.
// Steps without a schema (empty Schema) pass through untouched, so it is safe to
// register globally.
var SchemaValidationPostHook = engine.SchemaValidationPostHook

// ValidateJSONSchema validates value against a JSON Schema (the common LLM
// subset) and returns a list of human-readable violations ("" path = root).
var ValidateJSONSchema = engine.ValidateJSONSchema

// Judges
// ------

// RubricJudge scores a single output on multiple dimensions.
type RubricJudge = engine.RubricJudge

// PairwiseJudge compares two outputs and picks the stronger one.
type PairwiseJudge = engine.PairwiseJudge

// ConstraintJudge checks whether an output satisfies a stated rule.
type ConstraintJudge = engine.ConstraintJudge

// Judge is the base interface all judges implement.
type Judge = engine.Judge

// ScoreRequest is the input to RubricJudge.Score.
type ScoreRequest = engine.ScoreRequest

// RubricVerdict is the output of RubricJudge.Score.
type RubricVerdict = engine.RubricVerdict

// CompareRequest is the input to PairwiseJudge.Compare.
type CompareRequest = engine.CompareRequest

// PairwiseVerdict is the output of PairwiseJudge.Compare.
type PairwiseVerdict = engine.PairwiseVerdict

// CheckRequest is the input to ConstraintJudge.Check.
type CheckRequest = engine.CheckRequest

// ConstraintVerdict is the output of ConstraintJudge.Check.
type ConstraintVerdict = engine.ConstraintVerdict

// Completer is the narrow text-generation capability the LLM-backed judges need.
type Completer = engine.Completer

// NewLLMRubricJudge builds a rubric judge backed by a text generator.
var NewLLMRubricJudge = engine.NewLLMRubricJudge

// NewLLMConstraintJudge builds a constraint judge backed by a text generator.
var NewLLMConstraintJudge = engine.NewLLMConstraintJudge

// NewLLMPairwiseJudge builds a pairwise judge backed by a text generator.
var NewLLMPairwiseJudge = engine.NewLLMPairwiseJudge

// GeneratorCompleter adapts a text Generator to judge.Completer so engine
// generators can back real judges. The generator must return a TextResult.
var GeneratorCompleter = engine.GeneratorCompleter

// Cost tracking
// -------------

// CostManager is the public interface returned by Engine.Cost().
type CostManager = engine.CostManager

// UsageSummary aggregates cost metrics.
type UsageSummary = engine.UsageSummary

// UsageQuery is the input to cost queries.
type UsageQuery = engine.UsageQuery

// AgentUsage is a per-agent cost breakdown entry.
type AgentUsage = engine.AgentUsage

// AgentCostStats holds statistical cost data for an agent.
type AgentCostStats = engine.AgentCostStats

// EstimateRequest is the input to Cost().Estimate().
type EstimateRequest = engine.EstimateRequest

// CostEstimate is the output of Cost().Estimate().
type CostEstimate = engine.CostEstimate

// Budgets
// -------

// BudgetManager is the public interface returned by Engine.Budgets().
type BudgetManager = engine.BudgetManager

// Budget defines a (target, window, limit) spending triple.
type Budget = engine.Budget

// BudgetTarget identifies the entity a budget applies to. Only Kind ==
// TargetPlatformID is currently enforced; Create rejects other kinds.
type BudgetTarget = engine.BudgetTarget

// BudgetWindow is the rolling time window for a budget.
type BudgetWindow = engine.BudgetWindow

const BudgetWindowHour = engine.BudgetWindowHour

const BudgetWindowDay = engine.BudgetWindowDay

const BudgetWindowWeek = engine.BudgetWindowWeek

const BudgetWindowMonth = engine.BudgetWindowMonth

const BudgetWindowLifetime = engine.BudgetWindowLifetime

// BudgetLimit constrains usage by USD, tokens, and/or step count.
type BudgetLimit = engine.BudgetLimit

// BudgetAction is what happens when a budget is exceeded.
type BudgetAction = engine.BudgetAction

const BudgetBlock = engine.BudgetBlock

const BudgetDowngrade = engine.BudgetDowngrade

const BudgetNotify = engine.BudgetNotify

// TargetPlatformID is the BudgetTarget.Kind for per-user budgets.
const TargetPlatformID = engine.TargetPlatformID

// Caching
// -------

// Cache is a read-through cache for immutable engine objects (agents, prompts).
//
// Agents and prompts are addressed by slug+version and never mutated after
// creation, so they are safe to cache indefinitely. The cache sits in front of
// the database on every RunStep hot-path.
//
// Implement this interface with any backend you already use:
//   - In-process: use NewInProcessCache() (built-in, no dependencies)
//   - Redis: wrap go-redis or redigo
//   - Memcached: wrap gomemcache
//   - Ristretto / BigCache: wrap the client
//
// A nil Cache in Config disables caching (the default).
type Cache = engine.Cache

// CacheTTL controls how long immutable loom objects are cached.
// Agents and prompts are versioned and never mutated, so the default is
// effectively permanent — adjust only if your cache backend enforces eviction.
var CacheTTL = engine.CacheTTL

// InProcessCache is a lightweight in-process cache backed by a sync.Map.
// It supports optional TTL-based expiry, checked lazily on Get.
// Suitable for single-instance deployments or integration testing.
type InProcessCache = engine.InProcessCache

// NewInProcessCache returns a ready-to-use InProcessCache.
var NewInProcessCache = engine.NewInProcessCache

// Event bus
// ---------

// Message is one item published on a turn topic.
type Message = engine.Message

// Bus is the cross-agent channel fabric for a single turn.
type Bus = engine.Bus

// TopicAll subscribes to every topic.
const TopicAll = engine.TopicAll

// Pricing
// -------

// ModelPrice is the USD price per one million tokens for a model.
type ModelPrice = engine.ModelPrice

// ResultModel returns the model id a generator reported on a result's metadata,
// or "" if none.
var ResultModel = engine.ResultModel

// Garbage collection
// ------------------

// BranchGCConfig is a re-export of gc.Config for callers who import only loom.
type BranchGCConfig = engine.BranchGCConfig

// DefaultBranchGCConfig returns sensible production GC defaults.
var DefaultBranchGCConfig = engine.DefaultBranchGCConfig

// NewBranchGCWorker creates a branch GC worker using the engine's DB connection.
// The DB dialect is always sourced from the engine — it is a property of the
// connection, not a caller choice.
var NewBranchGCWorker = engine.NewBranchGCWorker

// SweepReport is returned by GC.DryRun.
type SweepReport = engine.SweepReport

// Errors & control-flow sentinels
// -------------------------------

// ErrSkip cancels the current step when returned from a pre-hook.
var ErrSkip = engine.ErrSkip

// IsSkip reports whether err signals a skip.
var IsSkip = engine.IsSkip

// RetryAnnotation carries metadata about why a retry was requested.
type RetryAnnotation = engine.RetryAnnotation

// RetryError signals a post-hook wants the step re-executed with updated hints.
type RetryError = engine.RetryError

// ErrRetryWith constructs a RetryError with the given annotation.
var ErrRetryWith = engine.ErrRetryWith

// ErrRetryScored is ErrRetryWith plus a score for the rejected draft and the
// draft itself, for RetryKeepBest steps: the engine keeps the lowest-scoring
// draft across attempts rather than failing on exhaustion. A non-positive score
// with a non-nil draft signals acceptance (keep it and stop retrying).
var ErrRetryScored = engine.ErrRetryScored

// IsRetry reports whether err is a RetryError.
var IsRetry = engine.IsRetry

// RetryAnnotationFrom extracts the RetryAnnotation if err is a RetryError.
var RetryAnnotationFrom = engine.RetryAnnotationFrom

// BudgetExceededError is returned when a step would exceed a configured budget.
type BudgetExceededError = engine.BudgetExceededError

// ErrNotFound is returned when a requested entity does not exist. Errors from
// the registries (Agents/Prompts/Sessions/Budgets/ResponseFormats) unwrap to it,
// so errors.Is(err, ErrNotFound) is the portable "does not exist" check; use
// errors.As with *NotFoundError to learn which entity and key were missing.
var ErrNotFound = engine.ErrNotFound

// NotFoundError identifies which entity was missing and by what key. It unwraps
// to ErrNotFound, so both errors.Is(err, ErrNotFound) and
// errors.As(err, &loom.NotFoundError{}) work.
type NotFoundError = engine.NotFoundError

// ErrDuplicateSlug is returned when an agent or prompt slug+version already exists.
var ErrDuplicateSlug = engine.ErrDuplicateSlug

// ErrSessionConflict is returned by Session update when the row's version no
// longer matches the in-memory copy — another writer updated it first, so this
// write would clobber theirs (optimistic-concurrency conflict).
var ErrSessionConflict = engine.ErrSessionConflict

// ErrInvalidConfig is returned by New when the Config is missing a required
// field or is otherwise unusable. Wrapped errors carry the specific reason.
var ErrInvalidConfig = engine.ErrInvalidConfig

// ErrGeneratorNotRegistered is returned when a step references a generator slug
// that was never registered with the engine. Wrapped errors name the slug.
var ErrGeneratorNotRegistered = engine.ErrGeneratorNotRegistered

// GenerationErrorKind classifies why a generator failed to produce a result, so
// applications can react differently (e.g. retry transport failures but surface
// provider rejections to the user).
type GenerationErrorKind = engine.GenerationErrorKind

// GenerationTransport is a network, stream, or context failure reaching or
// reading from the provider. The underlying error is available via Unwrap.
const GenerationTransport = engine.GenerationTransport

// GenerationRejected means the provider ran but returned a failed result
// (content policy, safety refusal, provider-side error).
const GenerationRejected = engine.GenerationRejected

// GenerationEmpty means the provider returned no usable result.
const GenerationEmpty = engine.GenerationEmpty

// GenerationError is returned when a generator fails to produce a usable result.
// Inspect it with errors.As(err, &loom.GenerationError{}) and switch on Kind.
type GenerationError = engine.GenerationError
